import type { ComponentProps } from "react"
import {
  ActivityIcon,
  AlertCircleIcon,
  ArrowLeftIcon,
  ArrowLeftRightIcon,
  ArrowRightIcon,
  AudioLinesIcon,
  BellIcon,
  BookOpenIcon,
  Building2Icon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleHelpIcon,
  CirclePlusIcon,
  CloudIcon,
  CoffeeIcon,
  ContainerIcon,
  CopyIcon,
  CreditCardIcon,
  DownloadIcon,
  FileBarChartIcon,
  FileTextIcon,
  GaugeIcon,
  GlobeIcon,
  ImageIcon,
  InfoIcon,
  LayoutDashboardIcon,
  LockIcon,
  LockKeyholeIcon,
  Loader2Icon,
  MessageSquareIcon,
  MinusIcon,
  MonitorIcon,
  MoreHorizontalIcon,
  PaintbrushIcon,
  PieChartIcon,
  PlusIcon,
  RefreshCwIcon,
  RepeatIcon,
  SearchIcon,
  ServerIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SquareIcon,
  SunIcon,
  TargetIcon,
  TerminalIcon,
  ThermometerIcon,
  TimerIcon,
  TrendingUpIcon,
  TrashIcon,
  TvIcon,
  UserIcon,
  UploadCloudIcon,
  Volume2Icon,
  WalletIcon,
  XIcon,
  ZapIcon,
  type LucideIcon,
} from "lucide-react"

const icons: Record<string, LucideIcon> = {
  ActivityIcon,
  AlertCircleIcon,
  ArrowLeftIcon,
  ArrowLeftRightIcon,
  ArrowRightIcon,
  AudioLinesIcon,
  BellIcon,
  BookOpenIcon,
  Building2Icon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleHelpIcon,
  CirclePlusIcon,
  CloudIcon,
  CoffeeIcon,
  ContainerIcon,
  CopyIcon,
  CreditCardIcon,
  DownloadIcon,
  FileBarChartIcon,
  FileTextIcon,
  GaugeIcon,
  GlobeIcon,
  ImageIcon,
  InfoIcon,
  LayoutDashboardIcon,
  LockIcon,
  LockKeyholeIcon,
  Loader2Icon,
  MessageSquareIcon,
  MinusIcon,
  MonitorIcon,
  MoreHorizontalIcon,
  PaintbrushIcon,
  PieChartIcon,
  PlusIcon,
  RefreshCwIcon,
  RepeatIcon,
  SearchIcon,
  ServerIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SunIcon,
  TargetIcon,
  TerminalIcon,
  ThermometerIcon,
  TimerIcon,
  TrendingUpIcon,
  TrashIcon,
  TvIcon,
  UserIcon,
  UploadCloudIcon,
  Volume2Icon,
  WalletIcon,
  XIcon,
  ZapIcon,
}

type IconPlaceholderProps = ComponentProps<"svg"> & {
  lucide: string
  tabler?: string
  hugeicons?: string
  phosphor?: string
  remixicon?: string
}

export function IconPlaceholder({
  lucide,
  tabler: _tabler,
  hugeicons: _hugeicons,
  phosphor: _phosphor,
  remixicon: _remixicon,
  ...props
}: IconPlaceholderProps) {
  void _tabler
  void _hugeicons
  void _phosphor
  void _remixicon

  const Icon = icons[lucide] ?? SquareIcon

  return <Icon {...props} />
}
